apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-argocd-dev
  namespace: argocd
  labels:
    app: helloworld
    environment: dev
    essesseff: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/essesseff-helloworld-springboot-templat/helloworld-argocd-dev
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

